[package]
name = "scintilla-sys"
version = "4.0.2"
authors = ["Serhii Plyhun <snuk188@gmail.com>"]
description = "Raw bindings to Scintilla Text Editor component"
homepage = "https://github.com/plyhun/plygui-scintilla"
repository = "https://github.com/plyhun/plygui-scintilla"
license = "MIT OR Apache-2.0"
build = "build.rs"
links = "scintilla"

[lib]
name = "scintilla_sys"
path = "src/lib.rs"

[dependencies]
libc = "~0.2"

[features]
win32 = ["cc", "embed-resource"]
gtk = []
qt = ["cc"]
curses = ["cc", "embed-resource"]
cocoa = []
default = ["qt"]

[build-dependencies]
cc = { version = "~1.0", optional = true }
embed-resource = { version = "~1.1", optional = true }